version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: git-sync
    main: ./cmd/git-sync
    binary: git-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: git-sync
    name_template: "git-sync_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: basmulder03
    name: git-projects-sync
  extra_files:
    - glob: scripts/install.ps1
    - glob: scripts/install.sh
